{
 "title": "Contacts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "QTD Requests Insert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_insert_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Insert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inserted_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD Requests Update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_update_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "updated_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD Requests Delete",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_delete_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Delete",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deleted_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}